### PR TITLE
fix: formatting triggered for zeros added after fractionDigits limit

### LINKED ISSUE #30: Adding 0's after the "fractionDigits" limit doesn't trigger formatting
- `$1.2211111111` > `$1.22` ❤️ 
- `$1.2200000000` > `$1.2200000000` 💔

### PR DESCRIPTION
**Pull request by gokullan**
Fixes #30, #33

Current Behaviour 
Adding 0s (after the decimal point) after the `fractionDigits` limit does not trigger formatting (See #30). This is due to the fact that the `setFormattedValue` function is called only when the numerical value of `value` changes.

Fix
In order to fix the above bug, a condition which checks for this specific case has been included in the code and handled appropriately: formatting is now triggered when the `fractionDigits` limit is exceeded. In the process of fixing this, another bug was uncovered (#36) and this PR includes that fix as well.

### CODE REVIEW

**Comment by fmaclen** [comment]
@gokullan thanks for submitting this fix, I'll try to review it today.

File: src/lib/CurrencyInput.svelte [hunk 1]
```diff
@@ -47,42 +47,56 @@
...
 		} else {
 			// The order of the following operations is *critical*
 			unformattedValue = unformattedValue.replace(isDecimalComma ? /\./g : /\,/g, ''); // Remove all group symbols
 			if (isDecimalComma) unformattedValue = unformattedValue.replace(',', '.'); // If the decimal point is a comma, replace it with a period
+			// If the zero-key has been pressed
+			// and if the current `value` is the same as the `value` before the key-press
+			// formatting may need to be done (Issue #30)
+			let prevValue = value;
 			value = parseFloat(unformattedValue);
+			if (event && prevValue == value) {
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:93]:
```suggestion

			// If the zero-key has been pressed
			// and if the current `value` is the same as the `value` before the key-press
			// formatting may need to be done (Issue #30)
			const previousValue = value;
			value = parseFloat(unformattedValue);

			if (event && previousValue === value) {
```

- Added extra line before the comment and before the `if` statement.
- Personal preference not using abbreviated names: `prevValue` > `previousValue`
- Use `const` if we are not going to reassign the value: `let prevValue` > `const previousValue`
- Match the value and the type: `prevValue == value` > `previousValue === value`

File: src/lib/CurrencyInput.svelte [hunk 2]
```diff
@@ -25,7 +25,7 @@
 			currency: currency,
 			style: 'currency',
 			maximumFractionDigits: maximumFractionDigits || 0,
-			minimumFractionDigits: minimumFractionDigits || 0
+			minimumFractionDigits: minimumFractionDigits || 0,
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:28]: This trailing comma was probably added by your editor formatter.

File: src/lib/CurrencyInput.svelte [hunk 3]
```diff
@@ -47,42 +47,56 @@
...
+			if (ignoreSymbols.includes(strippedUnformattedValue)) return;
 
-		// Set the starting caret positions
-		inputTarget = event.target as HTMLInputElement;
+			// Set the starting caret positions
+			inputTarget = event.target as HTMLInputElement;
 
+			// Reverse the value when minus is pressed
+			if (isNegativeAllowed && event.key === '-') value = value * -1;
+
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:73]: Remove empty line

File: src/lib/CurrencyInput.svelte [hunk 4]
```diff
@@ -47,42 +47,56 @@
...
+		}
+
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:75]: Keep this line empty, but remove the tabs/whitespaces.

**Review by fmaclen — CHANGES_REQUESTED** [review]
It looks great overall!
Just wanted to request some minor formatting changes if you don't mind.

The `on:blur` event probably needs a test but I can take care of that after your changes are merged.

File: src/lib/CurrencyInput.svelte (hunk 1 above)
Comment (gokullan) [reply src/lib/CurrencyInput.svelte:93]: Sure, will make the all required changes by tomorrow.

**Comment by gokullan** [comment]
@fmaclen I have made the required changes in my most recent commit. Let me know if anything else needs to be done.

**Comment by fmaclen** [comment]
@gokullan thanks for the contribution!
